github.com:
    users:
        richardaiand:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: richardaiand
